In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('abcnews-date-text.csv')

# Explore the first few rows to understand the data
print(df.head())

# Check the unique topics/categories
unique_topics = df['headline_text'].unique()
print("Unique Topics: ", unique_topics)

# Check the distribution of articles across topics
topic_distribution = df['headline_text'].value_counts()
print("Topic Distribution: \n", topic_distribution)

   publish_date                                      headline_text
0      20030219  aba decides against community broadcasting lic...
1      20030219     act fire witnesses must be aware of defamation
2      20030219     a g calls for infrastructure protection summit
3      20030219           air nz staff in aust strike for pay rise
4      20030219      air nz strike to affect australian travellers
Unique Topics:  ['aba decides against community broadcasting licence'
 'act fire witnesses must be aware of defamation'
 'a g calls for infrastructure protection summit' ...
 'wa delays adopting new close contact definition'
 'western ringtail possums found badly dehydrated in heatwave'
 'what makes you a close covid contact here are the new rules']
Topic Distribution: 
 national rural news                                            983
abc sport                                                      718
abc weather                                                    714
abc business news and m

In [ ]:
BOW-Bag of words

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
text=['aba decides against community broadcasting licence','act fire witnesses must be aware of defamation',
      'ambitious olsson wins triple jump']
#Initialize the vector
vectorizer=CountVectorizer()
#transform
x=vectorizer.fit_transform(text)
#get feature names(words)
feature_names=vectorizer.get_feature_names_out()
#Display BOW-Matrix
print('Feature names:\n',feature_names)
print()
print('BOW Matrix:\n')
print(x.toarray())

Feature names:
 ['aba' 'act' 'against' 'ambitious' 'aware' 'be' 'broadcasting' 'community'
 'decides' 'defamation' 'fire' 'jump' 'licence' 'must' 'of' 'olsson'
 'triple' 'wins' 'witnesses']

BOW Matrix:

[[1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0]]


In [ ]:
TF-IDF

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
text=['aba decides against community broadcasting licence','act fire witnesses must be aware of defamation',
      'ambitious olsson wins triple jump']

tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(text)

features_names_tfidf=tfidf.get_feature_names_out()

print('Feature Names(TF-IDF):\n',features_names_tfidf)
print()
print('TF-IDF Matrix:\n',x_tfidf.toarray())

Feature Names(TF-IDF):
 ['aba' 'act' 'against' 'ambitious' 'aware' 'be' 'broadcasting' 'community'
 'decides' 'defamation' 'fire' 'jump' 'licence' 'must' 'of' 'olsson'
 'triple' 'wins' 'witnesses']

TF-IDF Matrix:
 [[0.40824829 0.         0.40824829 0.         0.         0.
  0.40824829 0.40824829 0.40824829 0.         0.         0.
  0.40824829 0.         0.         0.         0.         0.
  0.        ]
 [0.         0.35355339 0.         0.         0.35355339 0.35355339
  0.         0.         0.         0.35355339 0.35355339 0.
  0.         0.35355339 0.35355339 0.         0.         0.
  0.35355339]
 [0.         0.         0.         0.4472136  0.         0.
  0.         0.         0.         0.         0.         0.4472136
  0.         0.         0.         0.4472136  0.4472136  0.4472136
  0.        ]]


In [6]:
import nltk

In [8]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize
text=input('Enter a statement:\n\t')
sent_token=sent_tokenize(text)
#print('Sentences:\n',sent_token)
for sent in sent_token:
    print(sent)
    print(len(sent))

print()
tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(sent_token)

features_names_tfidf=tfidf.get_feature_names_out()

print('Feature Names(TF-IDF):\n',features_names_tfidf)
print()
print('TF-IDF Matrix:\n',x_tfidf.toarray())


Enter a statement:
	commonwealth bank cuts fixed home loan rates. community urged to help homeless youth
commonwealth bank cuts fixed home loan rates.
45
community urged to help homeless youth
38

Feature Names(TF-IDF):
 ['bank' 'commonwealth' 'community' 'cuts' 'fixed' 'help' 'home' 'homeless'
 'loan' 'rates' 'to' 'urged' 'youth']

TF-IDF Matrix:
 [[0.37796447 0.37796447 0.         0.37796447 0.37796447 0.
  0.37796447 0.         0.37796447 0.37796447 0.         0.
  0.        ]
 [0.         0.         0.40824829 0.         0.         0.40824829
  0.         0.40824829 0.         0.         0.40824829 0.40824829
  0.40824829]]


In [ ]:
N-grams

In [11]:
import nltk
from nltk import ngrams
text='aba decides against community broadcasting licence'
tokens=nltk.word_tokenize(text)
#Generate bigrams
n=2
bigrams=list(ngrams(tokens,n))
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in bigrams:
    print(gram)

Original text:aba decides against community broadcasting licence 

Generated 2-grams:
('aba', 'decides')
('decides', 'against')
('against', 'community')
('community', 'broadcasting')
('broadcasting', 'licence')


In [13]:
import nltk
from nltk import ngrams
text='aba decides against community broadcasting licence'
tokens=nltk.word_tokenize(text)
#Generate n-grams
n=3
ngrams=list(ngrams(tokens,n))
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
 print(gram)



Original text:aba decides against community broadcasting licence

Generated 3-grams:
('aba', 'decides', 'against')
('decides', 'against', 'community')
('against', 'community', 'broadcasting')
('community', 'broadcasting', 'licence')


In [14]:
import nltk
from nltk import ngrams
text='aba decides against community broadcasting licence'
tokens=nltk.word_tokenize(text)
#Generate n-grams
n=4
ngrams=list(ngrams(tokens,n))
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
 print(gram)

Original text:aba decides against community broadcasting licence

Generated 4-grams:
('aba', 'decides', 'against', 'community')
('decides', 'against', 'community', 'broadcasting')
('against', 'community', 'broadcasting', 'licence')


In [15]:
#generate n-grams with list comprehension
n=2
text='aba decides against community broadcasting licence'
tokens=nltk.word_tokenize(text)
ngrams=[tokens[i:i+n] for i in range(len(tokens)-n+1)]
print(f"Original text:{text}")
print()
print(f"Generated {n}-grams:")
for gram in ngrams:
 print(gram)


Original text:aba decides against community broadcasting licence

Generated 2-grams:
['aba', 'decides']
['decides', 'against']
['against', 'community']
['community', 'broadcasting']
['broadcasting', 'licence']


In [ ]:
Onehot encoding

In [16]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
text=['aba decides against community broadcasting licence','act fire witnesses must be aware of defamation',
      'ambitious olsson wins triple jump']
#step 1- tokens
tokens=[word for sent in text for word in sent.lower().split()]
#step 2- vocabulary
vocabulary=list(set(tokens)) # unique words in the text
#initialize encoder
encoder=OneHotEncoder(categories=[vocabulary],sparse=False)
#Perform the one-hot encoding
one_hot_encoded=[]
for sent in text:
    sent_encoded=[]
    for word in sent.lower().split():
        word_index=vocabulary.index(word)
        word_vector=np.zeros(len(vocabulary))
        word_vector[word_index]=1
        sent_encoded.append(word_vector)
        one_hot_encoded.append(sent_encoded)

for sent in one_hot_encoded:
    print(sent)

[array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0.])]
[array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.]), array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [17]:
sent[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [18]:
sent[1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [19]:
len(sent)

5

In [20]:
type(sent)

list

In [ ]:
Word2vec

In [21]:
!pip install gensim


In [28]:
import gensim
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk
#sample text
text=['freedom records net profit for third successive',
 'funds allocated for domestic violence victims',
 'funds allocated for youth at risk']
tokenized_text=[word_tokenize(sentence.lower()) for sentence in text]
#Train Word2vec model
model=Word2Vec(sentences=tokenized_text,vector_size=20,window=5,min_count=1,workers=4)
#Find word vectors
vector_youth=model.wv['youth']
vector_risk=model.wv['risk']
#similarity b/w words
similarity=model.wv.similarity('funds','successive')
print(f"Vector for 'youth':{vector_youth}")
print('='*100)
print(f"Vector for 'risk':{vector_risk}")
print('='*100)
print(f"Similarity b/w 'word' and 'successive':{similarity}")


Vector for 'youth':[-0.04309844  0.01832869  0.02594942  0.02870969  0.03733459 -0.03083838
  0.00552807  0.03023641 -0.01420025 -0.03086761 -0.00205112 -0.04184474
 -0.02800006  0.03552269  0.0167627   0.03612835  0.03400124  0.03765371
 -0.01894577 -0.00280903]
Vector for 'risk':[-0.00788826  0.00160686 -0.02070315 -0.03841344 -0.00754004  0.01234897
 -0.00444013  0.02766831 -0.01371489  0.01130033  0.02727897  0.04172977
 -0.0072687  -0.04604071  0.02185276  0.00285892  0.03720954 -0.00406641
 -0.01319207 -0.04376505]
Similarity b/w 'word' and 'successive':0.029164906591176987


In [28]:
Doc2Vec

In [29]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from nltk.tokenize import word_tokenize
#sample text
documents=['freedom records net profit for third successive',
 'funds allocated for domestic violence victims',
 'funds allocated for youth at risk']
#Tokenize & tag documents
tagged_data=[TaggedDocument(words=word_tokenize(doc.lower()),
 tags=[str(i)]) for i,doc in enumerate(documents)]
print(tagged_data)


[TaggedDocument(words=['freedom', 'records', 'net', 'profit', 'for', 'third', 'successive'], tags=['0']), TaggedDocument(words=['funds', 'allocated', 'for', 'domestic', 'violence', 'victims'], tags=['1']), TaggedDocument(words=['funds', 'allocated', 'for', 'youth', 'at', 'risk'], tags=['2'])]


In [30]:
#Train Doc2vec model
model=Doc2Vec(vector_size=100,window=2,min_count=1,workers=5,epochs=20)
model.build_vocab(tagged_data)
model.train(tagged_data,total_examples=model.corpus_count,epochs=model.epochs)


In [32]:
vector_doc_1=model.infer_vector(word_tokenize("freedom records net profit for third successive"))

In [33]:
vector_doc_1

array([-5.1598279e-03,  3.7666087e-03,  3.8678725e-03,  3.2109481e-03,
       -1.5750297e-03,  1.2167619e-03,  4.3993276e-03,  9.2534305e-05,
        2.1115555e-03, -3.5271735e-03, -2.1526315e-03, -2.9060470e-03,
       -1.7513999e-03,  3.9840145e-03,  1.7849097e-03, -4.7744559e-03,
       -2.1094426e-03,  2.0156311e-05,  4.8355130e-03, -6.9864915e-04,
        3.0697761e-03, -3.3649136e-03,  1.0380092e-03,  2.0349792e-03,
        4.0504304e-04,  2.2423756e-03, -1.1903620e-03, -2.2822090e-03,
       -2.3566298e-03,  3.3246775e-03,  4.4913967e-03,  1.2507001e-03,
       -2.2881494e-03,  1.2604150e-03,  4.7452278e-03, -2.3397068e-03,
        1.3457796e-03, -3.1500545e-03,  1.4646767e-03,  2.4791963e-03,
       -4.6012364e-03, -1.1434144e-03,  2.7670967e-03, -4.7013494e-03,
        4.3227631e-03,  3.7469086e-03, -1.9827317e-03,  2.3259609e-03,
        1.4483843e-03,  3.8721075e-03, -7.2025496e-04, -2.9155153e-03,
        1.3057471e-03,  3.4958427e-03, -1.7218287e-03,  5.1882863e-03,
      

In [34]:
#find the most similar document
similar_doc=model.docvecs.most_similar(positive=[vector_doc_1])
print(f"vector for 'freedom records net profit for third successive':{vector_doc_1}")
print()
print(f"Most similar document:{similar_doc}")


vector for 'freedom records net profit for third successive':[-5.1598279e-03  3.7666087e-03  3.8678725e-03  3.2109481e-03
 -1.5750297e-03  1.2167619e-03  4.3993276e-03  9.2534305e-05
  2.1115555e-03 -3.5271735e-03 -2.1526315e-03 -2.9060470e-03
 -1.7513999e-03  3.9840145e-03  1.7849097e-03 -4.7744559e-03
 -2.1094426e-03  2.0156311e-05  4.8355130e-03 -6.9864915e-04
  3.0697761e-03 -3.3649136e-03  1.0380092e-03  2.0349792e-03
  4.0504304e-04  2.2423756e-03 -1.1903620e-03 -2.2822090e-03
 -2.3566298e-03  3.3246775e-03  4.4913967e-03  1.2507001e-03
 -2.2881494e-03  1.2604150e-03  4.7452278e-03 -2.3397068e-03
  1.3457796e-03 -3.1500545e-03  1.4646767e-03  2.4791963e-03
 -4.6012364e-03 -1.1434144e-03  2.7670967e-03 -4.7013494e-03
  4.3227631e-03  3.7469086e-03 -1.9827317e-03  2.3259609e-03
  1.4483843e-03  3.8721075e-03 -7.2025496e-04 -2.9155153e-03
  1.3057471e-03  3.4958427e-03 -1.7218287e-03  5.1882863e-03
 -1.9246866e-03  4.9265362e-03 -4.0118904e-03  2.9164637e-03
  7.3131447e-04 -2.69217

<ipython-input-34-9baca6c84fb8>:2: DeprecationWarning: Call to deprecated `docvecs` (The `docvecs` property has been renamed `dv`.).
  similar_doc=model.docvecs.most_similar(positive=[vector_doc_1])
