In [ ]:
1.Create a 3x3x3 array with random values using numpy in Python.

In [1]:
import numpy as np

random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[5.62513520e-01 8.03437316e-02 9.61608038e-01]
  [5.24925669e-01 9.90876280e-01 1.35095023e-01]
  [8.78715419e-01 6.59461487e-04 6.00628338e-01]]

 [[3.34848314e-01 9.38626437e-01 4.16537618e-01]
  [9.15512074e-01 5.53124810e-01 8.39661001e-01]
  [8.49239058e-01 5.42782195e-01 7.10099081e-01]]

 [[9.70723326e-01 9.19785146e-01 9.71314583e-01]
  [1.05069758e-01 4.28706077e-01 5.06574873e-01]
  [3.34353063e-01 5.15991811e-01 5.80453988e-01]]]


In [ ]:
2.Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal using numpy in python.

In [2]:
import numpy as np

matrix = np.zeros((5, 5))

for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
3.You can create an 8x8 matrix filled with a checkerboard pattern using NumPy in Python like this:

In [3]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
4.Normalize a 5 × 5 random matrix using numpy in Python.

In [4]:
import numpy as np

random_matrix = np.random.rand(5, 5)

mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)

normalized_matrix = (random_matrix - mean_value) / std_deviation

print("Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Random Matrix:
[[0.9304676  0.71469539 0.76997904 0.0462923  0.76326771]
 [0.21495729 0.1113909  0.49648484 0.68920469 0.05043509]
 [0.1166578  0.00421898 0.66989987 0.66256249 0.4396174 ]
 [0.07977604 0.4615104  0.80847105 0.62270095 0.82284989]
 [0.95427867 0.86762169 0.08049999 0.56591591 0.5065277 ]]

Normalized Matrix:
[[ 1.39122792  0.69708065  0.87493023 -1.45319707  0.85333964]
 [-0.91059547 -1.24377242 -0.00491084  0.61507613 -1.43986954]
 [-1.22682862 -1.58854849  0.55297181  0.52936719 -0.18785552]
 [-1.34547863 -0.11742491  0.99876047  0.4011311   1.04501773]
 [ 1.46782904  1.18905029 -1.34314964  0.21845152  0.02739743]]


In [ ]:
5.How to find common values between two arrays in Numpy in Python?

In [6]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print("Common Values:", common_values)

Common Values: [3 4 5]


In [ ]:
6.How to get the dates of  yesterday,today and tomorrow ?

In [7]:
import numpy as np
from datetime import datetime, timedelta

today = datetime.today().date()

yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

dates = np.array([yesterday, today, tomorrow])

print("Dates as NumPy array:", dates)

Dates as NumPy array: [datetime.date(2023, 9, 20) datetime.date(2023, 9, 21)
 datetime.date(2023, 9, 22)]


In [ ]:
7.Consider two random arrays A and B, check if they are equal

In [8]:

A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are equal.


In [ ]:
8.Create a random vector of size 10 and replace the maximum value by 0

In [9]:
import numpy as np

random_vector = np.random.rand(10)

max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print(random_vector)

[0.80800271 0.79941363 0.1911972  0.72576958 0.70769237 0.
 0.82100507 0.39402816 0.54388765 0.00929025]


In [ ]:
9.How to print all the values of an array

In [10]:

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

for row in arr_2d:
    for val in row:
        print(val)

1
2
3
4
5
6
7
8
9


In [ ]:
10.Subtract the mean of each row of a matrix

In [11]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)

matrix_minus_mean = matrix - row_means

print(matrix_minus_mean)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [ ]:
11.Consider a given vector. How to add one to each element indexed by a second vector(be
careful with repeated indices)?

In [12]:
import numpy as np

initial_vector = np.array([1, 2, 3, 4, 5])

indices = np.array([0, 2, 3])

result_vector = initial_vector.copy()

result_vector[indices] += 1

print(result_vector)

[2 2 4 5 5]


In [ ]:
12.How to get a Diagonal of Dot product ?

In [13]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

dot_product = np.dot(A, B)

diagonal = np.diagonal(dot_product)

print(diagonal)

[30 69 90]


In [ ]:
13.How to Find the Most Frequent Value in an Array?

In [20]:
import numpy as np

my_array = np.array([0,10,50])

unique_values, counts = np.unique(my_array, return_counts=True)

most_frequent_index = np.argmax(counts)

most_frequent_value = unique_values[most_frequent_index]

print(f"The most frequent value is {most_frequent_value} with {counts[most_frequent_index]} occurrences.")


The most frequent value is 0 with 1 occurrences.


In [ ]:
14.How to get the n-largest values of an array?

In [15]:
import numpy as np

arr = np.array([5, 2, 8, 1, 7, 3])

n = 3

n_largest = np.partition(arr, -n)[-n:]

print(n_largest)

[5 7 8]


In [ ]:
15.How to Create a Record Array from a Regular Array?

In [17]:
import numpy as np

regular_array = np.array([1, 2, 3, 4, 5])

record_array = np.rec.array(regular_array, dtype=[('my_column', int)])

print("Record Array:")
print(record_array)
print("Accessing 'my_column':", record_array.my_column)

Record Array:
[(1,) (2,) (3,) (4,) (5,)]
Accessing 'my_column': [1 2 3 4 5]


In [ ]:
16.How to swap two rows of an array ?

In [18]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

array[[0, 2]] = array[[2, 0]]

print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
17. Write Python code to reshape to the next dimension of numPy array.

In [23]:
import numpy as np

original_array = np.array([[1, 2], [3, 4], [5, 6]])

reshaped_array = original_array.reshape(-1, original_array.shape[0])

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np

olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

In [ ]:
1. Find Country index with max gold

In [2]:
import numpy as np

olympic_country = np.array(['GBR', 'Chine', 'RUS', 'US', 'KOR, JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

max_gold_index = np.argmax(olympic_country_gold)

country_with_max_gold = olympic_country[max_gold_index]

print(f"The country with the maximum gold medals is {country_with_max_gold} at index 
      {max_gold_index}.")

The country with the maximum gold medals is US at index 3.


In [ ]:
2. Country with Max Gold

In [3]:
import numpy as np

olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

max_gold_index = np.argmax(olympic_country_gold)

country_with_max_gold = olympic_country[max_gold_index]

print("Country with the most gold medals:", country_with_max_gold)

Country with the most gold medals: US


In [ ]:
3. Find Countries with More than 20 Gold

In [4]:
import numpy as np

olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

mask = olympic_country_gold > 20

countries_with_more_than_20_gold = olympic_country[mask]

print("Countries with more than 20 gold medals:", countries_with_more_than_20_gold)

Countries with more than 20 gold medals: ['GBR' 'China' 'RUS' 'US']


In [ ]:
4. Evaluate the dataset and print the medal:

1. print each country name with number of gold medals

2. print each country nale with total number of medals

In [5]:
import numpy as np

olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

for i in range(len(olympic_country)):
    country = olympic_country[i]
    gold = olympic_country_gold[i]
    silver = olympic_country_silver[i]
    bronze = olympic_country_bronze[i]
    total_medals = gold + silver + bronze
    print(f"Country: {country}, Gold Medals: {gold}, Total Medals: {total_medals}")

Country: GBR, Gold Medals: 29, Total Medals: 65
Country: China, Gold Medals: 38, Total Medals: 88
Country: RUS, Gold Medals: 24, Total Medals: 81
Country: US, Gold Medals: 46, Total Medals: 103
Country: KOR, Gold Medals: 13, Total Medals: 28
Country: JPN, Gold Medals: 7, Total Medals: 38
Country: GER, Gold Medals: 11, Total Medals: 36
